export const API_CONFIG = {
  BASE_URL: '/api',
  TOKEN: 'token_test1234',

  ENDPOINTS: {
    LOGIN: '/portalEmpleos/v1/login',
    REGISTER_CANDIDATE: '/portalEmpleos/v1/registerCandidateUser',
    REGISTER_EMPLOYER: '/portalEmpleos/v1/registerEmployerUser',
    GET_AVAILABLE_JOBS: '/portalEmpleos/v1/getAvailableJobs',
    GET_SKILLS_LIST: '/portalEmpleos/v1/getSkillsList',
    GET_COMPANIES_LIST: '/portalEmpleos/v1/getCompaniesList',
    GET_JOB_TYPE_LIST: '/portalEmpleos/v1/getJobTypeList',
    GET_LOCATIONS: '/portalEmpleos/v1/getLocations',
    CREATE_NEW_COMPANY: '/portalEmpleos/v1/createNewCompany',
    CREATE_NEW_JOB: '/portalEmpleos/v1/createNewJob',
    CREATE_JOB_OFFER: '/portalEmpleos/v1/createJobOffer',
    APPLY_FOR_A_JOB: '/portalEmpleos/v1/applyForAJob',
    GET_USER_APPLICATIONS: '/portalEmpleos/v1/getUserApplications',
    GET_APPLICATION_STATUS: '/portalEmpleos/v1/getApplicationStatus',
    GET_APPLICATIONS_WITH_COMPANY_ID: '/portalEmpleos/v1/getApplicationsWithCompanyId',
    GET_APPLICANTS_INFORMATION: '/portalEmpleos/v1/getApplicantsInformation',
    CHANGE_APPLICATION_STATUS: '/portalEmpleos/v1/changeApplicationStatus',
    UPLOAD_WORK_EXPERIENCE: '/portalEmpleos/v1/uploadWorkExperience',
    GET_STATS: '/portalEmpleos/v1/getStats',
  },
};
